name: Daily Data Pipeline

on:
  schedule:
    - cron: "30 22 * * *" # Runs daily at 10:30 PM UTC = 4:00 AM IST
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES }}" > ~/.dbt/profiles.yml
      - name: Run pipeline
        env:
          CONNECTION_ID: ${{ secrets.CONNECTION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          AUTH: ${{ secrets.AUTH }}
          GEMINI_API: ${{ secrets.GEMINI_API }}
          PINECONE_API: ${{ secrets.PINECONE_API }}
        run: python pipeline.py
